version: "3.9"

services:
  jupyter:
    container_name: jupyter
    build: .
    volumes:
      - ${PATH_WORK}/src:/app/src/
      - ${PATH_WORK}/data:/app/data/
    ports:
      - ${PORT}:8888
    environment:
      - JUPYTER_TOKEN=NO_TOKEN
