version: "3.9"

services:
  python:
    container_name: jupyter
    image: jupyter/minimal-notebook
    volumes:
      - ${PATH_WORK}
    ports:
      - ${PORT}:8888
    environment:
      - JUPYTER_TOKEN=NO_TOKEN
